### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by Fombi-Favour** [Abbas-Aljuaifari/The-Portfolio#3]
## Add a non-value to an attribute
- The `btn` value does not correspond to the `type` attribute of the element.
` 
        <nav>
            <button type="button btn" class="menu-button">
                 <span class="open" id="menu"></span>
            </button>
        </nav> `

**Comment by Abbas-Aljuaifari** [comment]
Thanks to all of you guys!!
![](https://media.giphy.com/media/FpaOqwlhaST0k/giphy.gif)
