### ISSUE TITLE
Portfolio-deployment 

### ISSUE THREAD

**Issue by MariamOsman11** [Abbas-Aljuaifari/The-Portfolio#9]
Abbas! you have done  good job here! I haven't find any issue with your deoployment.

**Comment by roshanasingh4** [comment]
Hey @Abbas-Aljuaifari your deployment seems to be working fine with pixel perfect features copied from the figma design, it looks great. No issues!

**Comment by Abbas-Aljuaifari** [comment]
THANKS, GUYS FOR THE NICE FEEDBACK!!

![](https://media.giphy.com/media/YRuFixSNWFVcXaxpmX/giphy.gif)
